set(_CATKIN_CURRENT_PACKAGE "TurtleMadero")
set(TurtleMadero_VERSION "0.0.0")
set(TurtleMadero_MAINTAINER "root <root@todo.todo>")
set(TurtleMadero_PACKAGE_FORMAT "2")
set(TurtleMadero_BUILD_DEPENDS "actionlib" "move_base_msgs" "rospy" "std_msgs")
set(TurtleMadero_BUILD_EXPORT_DEPENDS "actionlib" "move_base_msgs" "rospy" "std_msgs")
set(TurtleMadero_BUILDTOOL_DEPENDS "catkin")
set(TurtleMadero_BUILDTOOL_EXPORT_DEPENDS )
set(TurtleMadero_EXEC_DEPENDS "actionlib" "move_base_msgs" "rospy" "std_msgs")
set(TurtleMadero_RUN_DEPENDS "actionlib" "move_base_msgs" "rospy" "std_msgs")
set(TurtleMadero_TEST_DEPENDS )
set(TurtleMadero_DOC_DEPENDS )
set(TurtleMadero_URL_WEBSITE "")
set(TurtleMadero_URL_BUGTRACKER "")
set(TurtleMadero_URL_REPOSITORY "")
set(TurtleMadero_DEPRECATED "")